export const SIDEBAR_STUDENT_WIDTH = 108
export const HEADER_STUDENT_HEIGHT = 90

export const SIDEBAR_STUDENT_WIDTH_UNIT = `${SIDEBAR_STUDENT_WIDTH}px`
export const HEADER_STUDENT_HEIGHT_UNIT = `${HEADER_STUDENT_HEIGHT}px`
