name: Deploy  Dev Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:

      - name: Get the latest code
        uses: actions/checkout@v3.1.0
      - uses: actions/setup-node@master

      - name: Directory Permissions
        run: chmod -R 777  ./

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.3.4
        with:

          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
