name: Deploy  Dev Project on push
on:
  push:
    branches:
      - main
jobs:
  web-deploy:
    name: Deploy
    environment: dev
    runs-on: ubuntu-latest
    steps:

      - name: Get the latest code
        uses: actions/checkout@v4
      - uses: actions/setup-node@v4

      - name: Directory Permissions
        run: chmod -R 777  ./

      - name: 📂 Sync files
        uses: SamKirkland/FTP-Deploy-Action@v4.0.0
        with:
          local-dir: /dist
          server-dir: ./
          server: ${{ secrets.FTP_SERVER }}
          username: ${{ secrets.FTP_USERNAME }}
          password: ${{ secrets.FTP_PASSWORD }}
          exclude: |
            **/.git*
            **/.git*/**
            **/node_modules/**
            .env
